# Generated by Django 3.1.4 on 2021-01-03 23:25

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Article Page',
                'verbose_name_plural': 'Article Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
