# Generated by Django 4.1 on 2024-08-26 20:40

from django.db import migrations
import streams.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelistingpage',
            name='content',
            field=wagtail.fields.StreamField([('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
