# Generated by Django 3.1.4 on 2020-12-31 23:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('photos', '0002_auto_20201231_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='photospage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='photos.PhotoCategory'),
        ),
    ]
