# Generated by Django 3.1.4 on 2021-01-01 01:07

from django.conf import settings
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0004_photoslistingpage_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPhoto',
            new_name='Photo',
        ),
        migrations.AddField(
            model_name='photoslistingpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
    ]
