# Generated by Django 3.1.4 on 2021-01-01 01:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20210101_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoslistingpage',
            name='categories',
        ),
        migrations.AlterField(
            model_name='photoslistingpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('category', wagtail.snippets.blocks.SnippetChooserBlock('photos.PhotoCategory'))], blank=True, null=True),
        ),
    ]
