# Generated by Django 3.1.4 on 2021-01-01 01:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('photos', '0006_auto_20210101_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoslistingpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('category', wagtail.snippets.blocks.SnippetChooserBlock('photos.PhotoCategory'))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PhotosPage',
        ),
    ]
