# Generated by Django 3.1.4 on 2021-01-01 21:11

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20210101_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='photos.PhotoCategory'),
        ),
        migrations.AlterField(
            model_name='photocategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='A slug to identify photos by this category', max_length=255, verbose_name='slug'),
        ),
    ]
