# Generated by Django 3.1.4 on 2021-01-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20210101_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ManyToManyField(blank=True, to='photos.PhotoCategory'),
        ),
    ]
