# Generated by Django 3.1.4 on 2021-01-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20210103_2325'),
        ('photos', '0011_auto_20210103_1921'),
    ]

    operations = [
    ]
