# Generated by Django 4.1 on 2024-08-26 20:40

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0002_auto_20201230_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Add additional text', required=True))])), ('simple_richtext', streams.blocks.RichtextBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
