# Generated by Django 3.1.4 on 2020-12-30 19:32

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_auto_20201220_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Add additional text', required=True))])), ('full_richtext', streams.blocks.RichtextBlock()), ('docLink', wagtail.documents.blocks.DocumentChooserBlock(required=True, template='streams/title_and_link_block.html'))], blank=True, null=True),
        ),
    ]
